# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Cell": "00_core.ipynb",
         "Board": "00_core.ipynb",
         "Swoggle": "00_core.ipynb",
         "RandomAgent": "01_ai.ipynb",
         "BasicAgent": "01_ai.ipynb",
         "win_rates": "01_ai.ipynb",
         "swoggle_to_state_vector": "01_ai.ipynb",
         "action_from_number": "01_ai.ipynb"}

modules = ["core.py",
           "ai.py"]

git_url = "https://github.com/johnowhitaker/swoggle/tree/master/"


def custom_doc_links(name): return None
