# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Cell": "00_core.ipynb",
         "Board": "00_core.ipynb"}

modules = ["core.py"]

git_url = "https://github.com/johnowhitaker/swoggle/tree/master/"


def custom_doc_links(name): return None
